spring:
  application:
    name: feature-flags
  mvc:
    static-path-pattern: /**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
server:
  port: 8081
gg:
  jte:
    development-mode: true
management:
  endpoints:
    web:
      exposure:
        include: health, togglz, info, metrics
togglz:
  features:
    LAYOUT_NEW:
      enabled: true
      strategy: filial-id-strategy
      param:
        filialIds: "1,2,3,4,5"
  console:
    secured: false